export const CONSTANTS = {
  VALIDATION_ERROR_MESSAGES: {
    REQUIRED_FIELD: "Required field",
    INVALID_FILE: "Must be a valid file",
    INVALID_DATE: "Invalid date",
    INVALID_TIME: "Invalid time",
    INVALID_MAX_FILE: "Image must be maximum 2 mb.",
    INVALID_PASSWORD: "Invalid password",
    PASSWORDS_NOT_MATCH: "Passwords do not match",
    INVALID_EMAIL: "Invalid email",
    MUST_BE_BOOLEAN: "Must be a boolean value",
    PASSWORD_MIN_LENGTH: "Password must be at least 6 characters long",
    MUST_BE_VALID: "Must be a valid value",
    MUST_BE_NUMBER: "Must be a number",
    MUST_BE_POSITIVE: "Must be a positive number",
    MUST_BE_GREATER_THAN_ZERO: "Must be greater than 0",
    MUST_BE_ARRAY: "Must be an array",
    REQUIRED_MIN_ONE: "At least one is required",
  },
  API_RESPONSE_MESSAGES: {
    VALIDATION_ERROR: "Validation error",
    USER_HAS_NO_PERMISSION:
      "User does not have permission to perform this action",
    INVALID_TOKEN: "Invalid token",
    TOKEN_NOT_PROVIDED: "Token not provided",
    INVALID_CREDENTIALS: "Invalid email or password",
    USER_NOT_FOUND: "User not found",
    TRAINING_NOT_FOUND: "Training not found",
    TRAINING_PLAN_NOT_FOUND: "Training plan not found",
    TRAINING_ALREADY_PROGRESS: "Training is already in progress",
    ALREADY_HAS_TRAINING_IN_PROGRESS: "Already has a training in progress",
    EXPENSE_NOT_FOUND: "expense not found",
    EXPENSE_ALREADY_PAID: "This expense has already been paid",
    EXPENSE_IS_CANCELED: "This expense has been canceled",
    CREDIT_CARD_NOT_FOUND: "Credit card not found",
    CATEGORY_NOT_FOUND: "Category not found",
    SUB_CATEGORY_NOT_FOUND: "Sub category not found",
    TRANSTION_HISTORY_NOT_FOUND: "Transition history not found",
    USER_ALREADY_EXISTS: "User with this email already exists",
    INTERNAL_SERVER_ERROR: "Internal server error",
    STUDENT_ALREADY_HAS_TRAINING_PLAN:
      "The student already has an active training plan",
    PLAN_NOT_FOUND: "Training plan not found",
    INVALID_PASSWORD: "Invalid password",
    LOGIN_ERROR: "Error while trying to login",
  },
  COOKIES_KEYS: {
    TOKEN: "TOKEN",
    THEME: "THEME",
  },
};
